id: IFE5ABD74
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T21:41:57+00:00'
last_modified: '2022-06-09T04:32:46.283476+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19107
  title: 'མདོ་དབུས་མཐོ་སྒང་གི་རི་དྭགས་རྩ་ཆེན་སྐོར།

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A2CB:
      image_group_id: I2PD20304
      title: Volume 1 of mdo dbus mtho sgang gi ri dwags rtsa chen skor/
      total_pages: 262
      order: 1
      base_file: A2CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
