id: P008106
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19107
  title: 'མདོ་དབུས་མཐོ་སྒང་གི་རི་དྭགས་རྩ་ཆེན་སྐོར།

    '
  author: ''
  volumes:
    aed7e3d7f2994b299f3d2e9d3dc3b87b:
      image_group_id: I2PD20304
      title: ''
      volume_number: 1
      total_pages: 262
ebook_metadata:
  title: 'མདོ་དབུས་མཐོ་སྒང་གི་རི་དྭགས་རྩ་ཆེན་སྐོར།

    '
  author: ''
  sku: P008106
  cover: cover.jpg
  layers:
  - pagination
